version = "3.10.7"
runner.dialect = scala213
maxColumn = 100

indent.main = 2
indent.callSite = 2
indent.extendSite = 2

newlines.beforeCurlyLambdaParams = true
spaces.inImportCurlyBraces = false
spaces.inParentheses = false

trailingCommas = always
optIn.configStyleArguments = true

align.preset = none
rewrite.rules = [SortImports]
