rules = [
  OrganizeImports,
  RemoveUnused,
  ExplicitResultTypes,
  DisableSyntax
]

OrganizeImports {
  groupedImports = Explode
  removeUnused = true
}

RemoveUnused {
  imports = false
  privates = true
  locals = true
}

ExplicitResultTypes {
  memberKind = [Def, Val]
  skipSimpleDefinitions = false
}

DisableSyntax.var = "'var' is forbidden. Please use 'val' or 'def'."
DisableSyntax.return = "'return' is forbidden. Please write as an expression."
DisableSyntax.throw = "'throw' is forbidden. Please reconsider your exception design."
